# Community Vector Clustering (K-Means)
My next step was to download as many top subreddits as I seemed able (47) and about 1000 comments worth of content from each (done outside of jupyter). Next I created the dataset with 5000 top-occurring words.

In [24]:
import pandas as pd
import numpy as np
from random import randint
from scipy import linalg

feature_set = pd.read_csv('../data/data.csv')

X = np.transpose(feature_set.values)
m = X.shape[0]

# Intitialize Cenroids
k = 16
centroids = []
for i in range(0,k):
    j = randint(0,m-1)
    centroids.append(X[j,:])
    # List of array vectors

# Run K-Means
num_iters = 100
assign = np.array([0]*m)
for n in range(0,num_iters):
    for i in range(0,m):
        c_dist = []
        for c in range(0,k):
            c_dist.append(np.power((linalg.norm(X[i,:]-centroids[c])),2))
        c_dist = np.array(c_dist)
        c_index = np.unravel_index(np.argmin(c_dist),c_dist.shape)[0]
        assign[i] = c_index

    for j in range(0,k):
        assign_logic = np.array(np.equal(assign,j),dtype=int).reshape(m,1)
        this_assign = np.multiply(assign_logic,X)
        centroids[j] = np.mean(this_assign,axis=0)

assign_data = {'name':feature_set.columns,'cluster':assign}
assign_data = pd.DataFrame(assign_data,columns=['name','cluster'])
assign_data.to_csv('../data/assign.csv',index=False)
centroid_data = np.array(centroids)
np.savetxt('../data/centroids.csv', centroid_data, delimiter=',')

In [25]:
pd.read_csv('../data/assign.csv')

                   name  cluster
0               gadgets        3
1                sports        4
2                gaming        4
3                  pics        5
4             worldnews        2
5                videos        0
6             AskReddit        0
7                   aww        4
8                 funny        4
9                  news        2
10               movies        0
11                 blog        3
12                books        2
13              history        2
14                 food        4
15           philosophy        2
16                Jokes        4
17                  Art        9
18                  DIY        1
19                space        4
20        Documentaries        2
21           askscience        3
22          nottheonion        4
23        todayilearned        4
24      personalfinance        5
25                 gifs        4
26         listentothis       12
27                 IAmA        2
28        announcements        4
29      TwoXChromosomes        2
30               creepy        4
31              nosleep        4
32         GetMotivated        5
33       WritingPrompts        2
34          LifeProTips        1
35            EarthPorn        4
36    explainlikeimfive       10
37       Showerthoughts        4
38           Futurology        2
39     photoshopbattles        4
40    mildlyinteresting        4
41      dataisbeautiful       13
42                 tifu        4
43        OldSchoolCool        4
44        UpliftingNews        5
45  InternetIsBeautiful        4
46              science       15